//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_CR
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public int Rank { get; set; }
        public string Mountain { get; set; }
        public int HeightInMeter { get; set; }
        public int HeightInFt { get; set; }
        public int ProminenceInMeter { get; set; }
        public string ParentMountain { get; set; }
    }
}
